# Generated by Django 5.2 on 2025-04-23 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basefeild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('basefeild_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basefeild')),
                ('emp_id', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
            ],
            bases=('app.basefeild',),
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('basefeild_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basefeild')),
                ('roll', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('fees', models.IntegerField()),
            ],
            bases=('app.basefeild',),
        ),
    ]
