# Generated by Django 5.2 on 2025-04-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baseinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Studentproxt',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.baseinfo',),
        ),
    ]
